name: Test project

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build project
      run: |
        bash prepare.sh
        mkdir build
        cd build
        cmake ..
        make
    - name: Run GoogleTest
      run: ./build/majorminer_test

